import {Tabletop} from './tabletop.js';
import {TERRAINS,createGame,claim,place,discard,score,cells,key,validate,legalMoves} from './engine.js';
const $=s=>document.querySelector(s),colors=['#bb744b','#688fb6','#858b54','#ac7796'],defaults=['Amber','Azure','Sage','Rose'];
let game,rotation=0,selection=null,view=0,hints=true,notice='';
try{const saved=JSON.parse(localStorage.getItem('crown-country'));if(saved?.version===1&&saved.players?.length)game=saved;}catch{}
game??=createGame(['Amber','Azure']);view=game.active;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function art(type){const motifs={
 wheat:'<path d="M10 40L49 12M15 48L56 19M27 52L61 28" stroke="#a27c2d" stroke-width="3"/><path d="M18 30l-1-8m7 4 8 1m-3-5v-8m7 4 9 1M28 39v-9m6 5 9 1m-3-6v-9m8 4 9 1" stroke="#f4d68b" stroke-width="4"/>',
 forest:'<path d="M6 47L18 17l12 30zm21-12L39 5l12 30zm13 22 11-27 12 27z" fill="#244c3e"/><path d="M4 33L15 8l11 25zm22 22 11-28 11 28z" fill="#608158"/><path d="M18 44v10m21-20v10m12 10v8" stroke="#b5a978" stroke-width="3"/>',
 water:'<path d="M-8 17Q8 6 25 17t35 0 30 0M-8 34Q8 23 25 34t35 0 30 0M-8 51Q8 40 25 51t35 0 30 0" fill="none" stroke="#a7c9c5" stroke-width="3"/><path d="M39 24l8-7-1 10z" fill="#eee0ae"/>',
 grass:'<path d="M8 47l3-8 3 8m23-25 3-8 3 8M45 53l3-8 3 8M17 24l3-7 3 7" stroke="#697f46" stroke-width="2" fill="none"/><g fill="#e9d5a5"><circle cx="28" cy="39" r="3"/><circle cx="52" cy="13" r="2"/><circle cx="12" cy="13" r="2"/></g>',
 swamp:'<ellipse cx="21" cy="41" rx="19" ry="7" fill="#7a8776"/><ellipse cx="48" cy="19" rx="16" ry="7" fill="#7a8776"/><path d="M14 37V20m7 18V25m23-8V5m8 12V8" stroke="#5a6355" stroke-width="2"/><path d="M14 24v-7m7 12v-7m23-9V5" stroke="#d0b384" stroke-width="4"/>',
 mine:'<path d="M2 53L25 13l17 25 8-12 16 29z" fill="#464f5b"/><path d="M25 13L14 33l12-6 10 4z" fill="#a0a6a5"/><path d="M33 53V42a8 8 0 0 1 16 0v11" fill="#252e35"/><path d="M34 47l6-5 4 6-5 4z" fill="#d9b768"/>',
 castle:'<path d="M11 52V22h12v8h18v-8h12v30z" fill="#e7d9b9"/><path d="M9 17h6v6h5v-6h6v15H9zm29 0h6v6h5v-6h6v15H38z" fill="#eee4cb"/><path d="M25 52V41a7 7 0 0 1 14 0v11" fill="#5c6658"/><path d="M32 30V6m0 0h15l-4 6H32" stroke="#d4b677" stroke-width="2" fill="#c18a51"/>'
};return `<svg viewBox="0 0 64 64" aria-hidden="true">${motifs[type]}</svg>`;}
function land(c){return `<span class="land ${c.type}">${art(c.type)}${c.crowns?`<span class="crowns">${'♛'.repeat(c.crowns)}</span>`:''}</span>`;}
function domino(d){return `<span class="domino" role="img" aria-label="${d.halves.map(c=>`${TERRAINS[c.type].name}, ${c.crowns} crowns`).join(' and ')}">${d.halves.map(land).join('')}</span>`;}
function save(){try{localStorage.setItem('crown-country',JSON.stringify(game));}catch{notice='This browser cannot save the game. Keep this tab open.';}}
function activeDomino(){return game.phase==='place'?game.current[game.turn]:null;}
let table;
function render(){const active=game.players[game.active],d=activeDomino(),canPlace=!!d;const moves=d?legalMoves(active.board,d):[];const error=selection&&d?validate(active.board,d,selection.x,selection.y,rotation):null;
if(!$('#game-canvas')){$('#app').innerHTML='<canvas id="game-canvas" tabindex="0" aria-label="Shared kingdom tabletop. Drag to pan, pinch or scroll to zoom. Use player buttons to focus a kingdom. Use Suggest spot to preview a legal placement, arrow keys to adjust, and Place to confirm."></canvas><div id="hud"></div>';table=new Tabletop($('#game-canvas'),{art,onSelect:select,onView:id=>{view=id;render();},onZoom:n=>{if($('#zoom-level'))$('#zoom-level').textContent=n+'%';}});}
const status={draft:'Choose your first domino',place:'Place your domino',claim:'Choose your next domino',finished:'The kingdoms are complete'}[game.phase];
$('#hud').innerHTML=`<div class="game-top"><header><a href="./" class="brand">♛ <span>Crown <i>&</i> Country</span></a><nav><button id="rules" aria-label="How to play">?</button><button id="new">New game</button><button id="fullscreen" aria-label="Toggle fullscreen">⛶</button></nav></header><div class="players">${game.players.map((p,i)=>`<button class="player ${game.active===i?'active':''} ${view===i?'viewed':''}" data-view="${i}" style="--player:${colors[i]}"><span class="player-icon">♜</span><span>${esc(p.name)}<small>${game.active===i&&game.phase!=='finished'?'Your turn':`${p.placed} / 12 lands`}</small></span><strong>${score(p.board).total}<small>pts</small></strong></button>`).join('')}</div></div>
<div class="camera-tools"><button id="focus" title="Focus active kingdom" aria-label="Focus active kingdom">⌖</button><button id="overview" title="Show whole table" aria-label="Show whole table">▦</button><button id="zoom-in" aria-label="Zoom in">+</button><span id="zoom-level">100%</span><button id="zoom-out" aria-label="Zoom out">−</button><button id="scores" title="Score details" aria-label="Score details">♛</button></div>
<section class="turn-dock"><div class="turn-title"><span class="turn-dot" style="background:${colors[game.active]}"></span><strong>${esc(active.name)}</strong><span>${status}</span><small>${game.phase==='draft'?'Opening draft':`Round ${game.round}/${game.players.length===2?6:12}`}</small></div>${['draft','claim'].includes(game.phase)?`<div class="draft-list">${game.market.map(d=>`<button class="draft-card ${d.owner!==null?'claimed':''}" data-claim="${d.id}" ${d.owner!==null?'disabled':''}><span class="draft-number">${String(d.id).padStart(2,'0')}</span>${domino(d)}<span class="claim-label">${d.owner!==null?'♜ '+esc(game.players[d.owner].name):'Claim land'}</span></button>`).join('')}</div>`:canPlace?`<div class="placement-bar"><div class="in-hand">${domino(d)}<span>#${d.id}</span></div><button id="rotate" class="secondary">↻ Rotate</button><button id="suggest" class="secondary">Suggest spot</button><button id="confirm" class="primary" ${!selection||error?'disabled':''}>Place ✓</button>${!moves.length?'<button id="discard" class="secondary">Discard</button>':''}</div>`:`<button id="results" class="primary wide">See final standings ♛</button>`}<p class="feedback" role="status">${esc(notice||error||(selection&&canPlace?'Ready to place. Confirm when you’re happy.':canPlace?'Tap a square to preview. Drag to explore; pinch to zoom.':'Lower numbers play first next round.'))}</p></section>`;
$('#rules').onclick=rules;$('#new').onclick=setup;$('#scores').onclick=scoreDetails;$('#focus').onclick=()=>{view=game.active;render();table.focus(game.active);};$('#overview').onclick=()=>table.overview();$('#zoom-in').onclick=()=>table.zoom(1.2);$('#zoom-out').onclick=()=>table.zoom(1/1.2);$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else {notice='Use your browser’s Add to Home Screen for a full-screen view.';render();}}catch{notice='Fullscreen is unavailable in this browser.';render();}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=+b.dataset.view;render();table.focus(view);});document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>act(()=>claim(game,+b.dataset.claim)));$('#rotate')?.addEventListener('click',rotate);$('#suggest')?.addEventListener('click',()=>{const m=moves.find(m=>!selection||m.x!==selection.x||m.y!==selection.y||m.r!==rotation)||moves[0];if(m){selection={x:m.x,y:m.y};rotation=m.r;view=game.active;render();table.focus(view);}});$('#confirm')?.addEventListener('click',()=>selection&&act(()=>place(game,selection.x,selection.y,rotation)));$('#discard')?.addEventListener('click',()=>act(()=>discard(game)));$('#results')?.addEventListener('click',results);
table.setState({game,view,colors,hints,selection,rotation});}
function select(x,y){if(!activeDomino())return;selection={x,y};view=game.active;notice='';render();}
function rotate(){if(!activeDomino())return;rotation=(rotation+1)%4;render();}
function act(fn){try{const previous=game.active;fn();selection=null;rotation=0;notice='';view=game.active;save();render();if(previous!==game.active)table.focus(game.active);if(game.phase==='finished')results();}catch(e){notice=e.message;render();}}
function scoreDetails(){const p=game.players[view],s=score(p.board);show(`<button class="close" data-close aria-label="Close">×</button><div class="eyebrow">${esc(p.name)}’S KINGDOM</div><h2>${s.total} victory points</h2><p>Each connected region scores its land × crowns.</p><div class="regions">${s.regions.length?s.regions.map(r=>`<div><span>${TERRAINS[r.type].name}</span><span>${r.size} × ${r.crowns} ♛</span><strong>${r.points}</strong></div>`).join(''):'Place your first domino to start building.'}</div><p>${p.placed} placed · ${p.discarded} discarded</p>`);}
document.addEventListener('keydown',e=>{if($('#modal').open||['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(e.key.toLowerCase()==='r'){e.preventDefault();rotate();}if(document.activeElement===$('#game-canvas')&&activeDomino()){const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();const s=selection||{x:1,y:0};select(Math.max(-4,Math.min(4,s.x+delta[0])),Math.max(-4,Math.min(4,s.y+delta[1])));$('#game-canvas').focus();}if(e.key==='Enter'&&selection&&!validate(game.players[game.active].board,activeDomino(),selection.x,selection.y,rotation))act(()=>place(game,selection.x,selection.y,rotation));}});

function show(html){const m=$('#modal');m.innerHTML=html;if(!m.open)m.showModal();m.querySelector('[data-close]')?.addEventListener('click',()=>m.close());}
function setup(){show(`<button class="close" data-close aria-label="Close">×</button><div class="modal-emblem">♛</div><div class="eyebrow">A PLACE AT THE TABLE</div><h2>A kingdom of your own.</h2><p>Gather around one screen. Your next great little kingdom is only twelve dominoes away.</p><label class="field-label" for="count">Players</label><div class="count-options">${[1,2,3,4].map(n=>`<button data-count="${n}" class="${n===2?'selected':''}">${n}<small>${n===1?'Solo':'Players'}</small></button>`).join('')}</div><div id="names"></div><p class="setup-note" id="mode-note"></p><button id="start" class="primary wide">Let’s build a kingdom →</button><small class="setup-foot">A new game replaces the saved game on this device.</small>`);let count=2;function fields(){ $('#names').innerHTML=Array.from({length:count},(_,i)=>`<label class="name-field"><span style="color:${colors[i]}">♜</span><input maxlength="20" aria-label="Player ${i+1} name" value="${defaults[i]}"></label>`).join('');$('#mode-note').textContent=count===1?'Solo practice: choose one of four lands each round; the others are discarded. Beat your own score.':count===2?'Two crowns each: draft twice per round. Six rounds, twelve dominoes per kingdom.':'One crown each: draft once per round. Twelve rounds, twelve dominoes per kingdom.';}fields();document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{count=+b.dataset.count;document.querySelectorAll('[data-count]').forEach(x=>x.classList.toggle('selected',x===b));fields();});$('#start').onclick=()=>{game=createGame([...document.querySelectorAll('#names input')].map((v,i)=>v.value.trim()||defaults[i]));view=game.active;selection=null;rotation=0;notice='';save();$('#modal').close();render();table.focus(game.active);};}
function rules(){show(`<button class="close" data-close aria-label="Close">×</button><div class="eyebrow">THE ROYAL HANDBOOK</div><h2>Your whole table, everywhere.</h2><p>Drag the table to explore. Pinch or scroll to zoom. Tap a player to focus their kingdom, or ▦ to see the whole table. Tap a square, rotate, and confirm your placement.</p><ol class="rules-list"><li><b>Claim your first domino.</b> The opening order is random. Lower-numbered lands give you an earlier turn in the next round.</li><li><b>Place, then claim.</b> Add your reserved domino, then choose your next one. In a two-player game, each player has two turns per round.</li><li><b>Make a match.</b> At least one new square must touch matching terrain, or your castle. Rotate with R. Select a square, then confirm.</li><li><b>Stay within 5 × 5.</b> The dotted canvas gives you room to expand in any direction. Your castle need not be in the center. Only discard when no legal placement exists.</li><li><b>Land × crowns = points.</b> Score each connected terrain region separately. A region without crowns scores zero. Largest region breaks tied scores; remaining ties share victory.</li></ol><p class="setup-note">Solo is a practice variant: pick one of four lands for 12 rounds. Three players also discard the unclaimed land. Optional bonus rules are not enabled.</p><button class="primary wide" id="back">Back to the table →</button>`);$('#back').onclick=()=>$('#modal').close();}
function ranked(){return game.players.map(p=>({...p,...score(p.board)})).sort((a,b)=>b.total-a.total||b.largest-a.largest);}
function standings(){return `<div class="standings">${ranked().map((p,i)=>`<div><span>${i+1}. ${esc(p.name)}</span><strong>${p.total} pts</strong></div>`).join('')}</div>`;}
function results(){const ranks=ranked(),winners=ranks.filter(p=>p.total===ranks[0].total&&p.largest===ranks[0].largest);show(`<button class="close" data-close aria-label="Close">×</button><div class="modal-emblem">♛</div><div class="eyebrow">THE FINAL CHAPTER</div><h2>${game.players.length===1?'A kingdom well built.':winners.map(p=>esc(p.name)).join(' & ')+(winners.length>1?' share the crown.':' takes the crown.')}</h2>${standings()}<p>${game.players.length===1?`Your kingdom scored ${ranks[0].total} points. Play again and try a different strategy.`:'Scores count connected land × crowns. Largest territory breaks a tied score.'}</p><button id="again" class="primary wide">Build another kingdom →</button>`);$('#again').onclick=setup;}
render();table.focus(game.active);try{if(!localStorage.getItem('crown-country'))setup();}catch{setup();}
