import {cells,key,score,validate,legalMoves,TERRAINS} from './engine.js';
export const CELL=48, BOARD=432;
export const origin=id=>({x:(id%2)*600,y:Math.floor(id/2)*600});
export function boardHit(x,y,count){for(let id=0;id<count;id++){const o=origin(id),cx=Math.floor((x-o.x)/CELL),cy=Math.floor((y-o.y)/CELL);if(cx>=0&&cx<9&&cy>=0&&cy<9)return {id,x:cx-4,y:cy-4};}return null;}
export class Tabletop{
 constructor(canvas,{art,onSelect,onView,onZoom}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onSelect=onSelect;this.onView=onView;this.onZoom=onZoom;this.camera={x:216,y:216,z:1};this.pointers=new Map();this.images={};this.hover=null;for(const type of [...Object.keys(TERRAINS),'castle']){const img=new Image();img.onload=()=>this.draw();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(art(type).replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));this.images[type]=img;}this.resize=new ResizeObserver(()=>{this.measure();if(this.state)this.focus(this.state.view);});this.resize.observe(canvas);this.bind();}
 measure(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*dpr);this.canvas.height=Math.round(this.h*dpr);this.dpr=dpr;}
 setState(state){this.state=state;this.moves=state.game.phase==='place'?legalMoves(state.game.players[state.game.active].board,state.game.current[state.game.turn]):[];this.draw();}
 limits(){let top=document.querySelector('.game-top')?.getBoundingClientRect().bottom||120;const bottom=document.querySelector('.turn-dock')?.getBoundingClientRect().height||140;if(this.w<=600)top=Math.max(top,document.querySelector('.camera-tools')?.getBoundingClientRect().bottom||0);return {top:top+12,bottom:bottom+24};}
 focus(id){if(!this.w)this.measure();const {top,bottom}=this.limits(),o=origin(id);this.camera={x:o.x+216,y:o.y+195,z:Math.max(.28,Math.min(1.4,(this.w-30)/480,(this.h-top-bottom)/510))};this.centerY=top+(this.h-top-bottom)/2;this.draw();}
 overview(){const {top,bottom}=this.limits(),n=this.state.game.players.length;const width=n>1?1032:432,height=n>2?1032:432;this.camera={x:width/2,y:height/2-15,z:Math.max(.16,Math.min((this.w-36)/(width+60),(this.h-top-bottom)/(height+110)))};this.centerY=top+(this.h-top-bottom)/2;this.draw();}
 world(x,y){return {x:(x-this.w/2)/this.camera.z+this.camera.x,y:(y-(this.centerY??this.h/2))/this.camera.z+this.camera.y};}
 zoom(factor,x=this.w/2,y=this.centerY??this.h/2){const before=this.world(x,y);this.camera.z=Math.max(.16,Math.min(2.8,this.camera.z*factor));const after=this.world(x,y);this.camera.x+=before.x-after.x;this.camera.y+=before.y-after.y;this.draw();}
 dragAt(clientX,clientY,pointerType='mouse'){
   const rect=this.canvas.getBoundingClientRect();
   const screen={x:clientX-rect.left,y:clientY-rect.top-(pointerType==='touch'?54:0)};
   const w=this.world(screen.x,screen.y), hit=boardHit(w.x,w.y,this.state.game.players.length);
   const surface=document.elementFromPoint?.(clientX,clientY);
   const onCanvas=!surface||surface===this.canvas;
   const target=onCanvas&&hit?.id===this.state.game.active?hit:null;
   const d=this.state.game.current[this.state.game.turn];
   const error=!target?'Drop on the active kingdom.':validate(this.state.game.players[this.state.game.active].board,d,target.x,target.y,this.state.rotation);
   this.drag={screen,target,error};this.hover=null;this.draw();
   return this.drag;
 }
 endDrag(){this.drag=null;this.hover=null;this.draw();}
 bind(){const c=this.canvas;const point=e=>{const r=c.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};c.addEventListener('pointerdown',e=>{if(this.drag)return;c.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,point(e));this.start=point(e);this.dragged=false;if(this.pointers.size>1)this.dragged=true;});c.addEventListener('pointermove',e=>{if(this.drag)return;const p=point(e),old=this.pointers.get(e.pointerId);if(old){const before=[...this.pointers.values()];this.pointers.set(e.pointerId,p);const after=[...this.pointers.values()];if(after.length===2){this.dragged=true;const distance=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);const mid=a=>({x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2});const m=mid(after),b=mid(before);this.zoom(distance(after)/Math.max(1,distance(before)),b.x,b.y);this.camera.x-=(m.x-b.x)/this.camera.z;this.camera.y-=(m.y-b.y)/this.camera.z;}else if(this.dragged||Math.hypot(p.x-this.start.x,p.y-this.start.y)>7){this.dragged=true;this.camera.x-=(p.x-old.x)/this.camera.z;this.camera.y-=(p.y-old.y)/this.camera.z;}this.hover=null;this.draw();}else if(e.pointerType==='mouse'){const w=this.world(p.x,p.y);this.hover=boardHit(w.x,w.y,this.state.game.players.length);this.draw();}});const finish=e=>{if(!this.pointers.has(e.pointerId))return;const p=point(e),tap=!this.dragged&&this.pointers.size===1;this.pointers.delete(e.pointerId);if(tap){const w=this.world(p.x,p.y),hit=boardHit(w.x,w.y,this.state.game.players.length);if(hit){if(hit.id!==this.state.game.active)this.onView(hit.id);else this.onSelect(hit.x,hit.y);}}if(this.pointers.size)this.dragged=true;};c.addEventListener('pointerup',finish);c.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.dragged=true;});c.addEventListener('pointerleave',()=>{this.hover=null;this.draw();});c.addEventListener('wheel',e=>{e.preventDefault();if(this.drag)return;const p=point(e);this.zoom(Math.exp(-e.deltaY*.0015),p.x,p.y);},{passive:false});}
 tile(c,x,y,alpha=1){const ctx=this.ctx;ctx.globalAlpha=alpha;ctx.fillStyle=c.type==='castle'?'#788e64':TERRAINS[c.type].color;ctx.fillRect(x+1,y+1,46,46);const img=this.images[c.type];if(img?.complete&&img.naturalWidth)ctx.drawImage(img,x+1,y+1,46,46);if(c.crowns){ctx.font='bold 17px Georgia';ctx.fillStyle='#ffe59b';ctx.shadowColor='#28231a';ctx.shadowBlur=3;ctx.fillText('♛'.repeat(c.crowns),x+3,y+43);ctx.shadowBlur=0;}ctx.globalAlpha=1;}
 draw(){if(!this.state||!this.w)return;const ctx=this.ctx,{game,colors,hints,rotation,selection}=this.state;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.fillStyle='#172f2b';ctx.fillRect(0,0,this.w,this.h);ctx.save();ctx.translate(this.w/2,this.centerY??this.h/2);ctx.scale(this.camera.z,this.camera.z);ctx.translate(-this.camera.x,-this.camera.y);const a=this.world(0,0),b=this.world(this.w,this.h);ctx.fillStyle='#25413a';for(let x=Math.floor(a.x/48)*48;x<b.x;x+=48)for(let y=Math.floor(a.y/48)*48;y<b.y;y+=48){ctx.beginPath();ctx.arc(x,y,1,0,7);ctx.fill();}game.players.forEach((p,id)=>{const o=origin(id),active=id===game.active&&game.phase!=='finished';ctx.fillStyle='#102621';ctx.shadowColor='#071b18';ctx.shadowBlur=20;ctx.fillRect(o.x-18,o.y-74,468,548);ctx.shadowBlur=0;ctx.fillStyle=active?'#cfb57e':'#6e8a7c';ctx.fillRect(o.x-18,o.y-74,468,3);ctx.font='26px Georgia';ctx.fillStyle='#e8e4cf';ctx.fillText(p.name.slice(0,20),o.x,o.y-32);ctx.font='13px sans-serif';ctx.fillStyle=colors[id];ctx.fillText(active?'● PLAYING NOW':`${p.placed} / 12 DOMINOES`,o.x,o.y-10);ctx.textAlign='right';ctx.font='26px Georgia';ctx.fillStyle='#dbc18c';ctx.fillText(`${score(p.board).total} pts`,o.x+432,o.y-31);ctx.textAlign='left';for(let y=-4;y<=4;y++)for(let x=-4;x<=4;x++){const px=o.x+(x+4)*48,py=o.y+(y+4)*48,c=p.board[key(x,y)];ctx.fillStyle=Math.abs(x)<=2&&Math.abs(y)<=2?'#29463a':'#1d382f';ctx.fillRect(px+1,py+1,46,46);if(c)this.tile(c,px,py);else{ctx.fillStyle='#536c55';ctx.fillRect(px+23,py+23,2,2);if(active&&hints&&this.moves.some(m=>m.x===x&&m.y===y&&m.r===rotation)){ctx.strokeStyle='#8ea974';ctx.setLineDash([3,4]);ctx.strokeRect(px+3,py+3,42,42);ctx.setLineDash([]);}}}ctx.font='12px sans-serif';ctx.fillStyle='#8a9c7e';ctx.fillText('5 × 5 KINGDOM  ·  LAND × CROWNS',o.x,o.y+457);if(active&&game.phase==='place'){const target=this.drag?this.drag.target:(this.hover?.id===id?this.hover:selection);if(target){const d=game.current[game.turn],err=validate(p.board,d,target.x,target.y,rotation);for(const c of cells(d,target.x,target.y,rotation)){const px=o.x+(c.x+4)*48,py=o.y+(c.y+4)*48;if(!p.board[key(c.x,c.y)])this.tile(c,px,py,.8);ctx.strokeStyle=err?'#ed8f76':'#f4dca0';ctx.lineWidth=3;ctx.strokeRect(px+2,py+2,44,44);ctx.lineWidth=1;}}}});ctx.restore();
 if(this.drag&&!this.drag.target){
   const d=game.current[game.turn],z=this.camera.z;
   ctx.save();ctx.translate(this.drag.screen.x,this.drag.screen.y);ctx.scale(z,z);
   for(const c of cells(d,0,0,rotation))this.tile(c,c.x*48-24,c.y*48-24,.8);
   ctx.restore();
 }
 this.onZoom?.(Math.round(this.camera.z*100));}
}
